### PR TITLE
SpatialScene::play_buffered optimizations

### PR DESCRIPTION
**Pull request by OlegOAndreev**
This is mostly the continuation of https://github.com/Ralith/oddio/pull/89

Four changes:
1. The most important one: do not call `Ring::sample` for every sample, process in chunks like the `Spatial::play` already does. Easily gives 50-60% perf improvement.
2. Specialize `FramesSignal::sample` for cases when the the delta is integer (i.e. interval / rate == 1.0), 10% perf improvement.
3. Do not re-initialize scratch buffer for every signal, perf improvement depends on the number of mixed signals.
4. (Not particularly related to the current PR, but I did not want to open a tiny PR just for it): fast-path for `Gain::sample` when the gain is constant.

### CODE REVIEW

**Comment by Ralith** [comment]
Whoops, this slipped through the cracks. Would you mind rebasing?

**Comment by Ralith** [comment]
The repeated merges and duplicate commits wrt. main make this difficult to review. Could you rebase instead?

**Comment by OlegOAndreev** [comment]
> The repeated merges and duplicate commits wrt. main make this difficult to review. Could you rebase instead?

I have a rather limited experience with Git outside of committing/merging so I would rather close this PR and reopen a new one by making a new fork of the repository.

**Comment by OlegOAndreev** [comment]
Opened #95 instead of this PR.

**Pull request closed without merging**
